### ISSUE TITLE
Return Advanced Properties ? 

### ISSUE THREAD

**Issue by melMass** [jeremyvizzini/MediaInfoKit#3]
# The Issue

I'm trying to retrieve the **frameCount** of a stream.

I added to the **MIKConstants** header :
```C++
MIK_EXPORT MIKValueKey const MIKValueKeyFrameCount;
```

I added to the **MIKConstants** m file :
```C++
MIKValueKey const MIKValueKeyFrameCount = @"Frame count";
```

But it still returns **nil**, do you know how to implement Advanced Metadata as such ?

Thanks

**Comment by jeremyvizzini** [comment]
MediaInfoKit uses MediaInfoLib to retrieve metadata (MediaInfoKit is just a wrapper). If you compile and test the objective-c demo application, the interface displays all information returned by the library.

Are you sure that "Frame count" can be returned by the library ? Even if the library handle this information, you have to be sure that the file you read contains this information. Otherwise, the result would be nil. 

Another solution would be to use the frame rate and the duration to compute the count but the result will not be accurate.

**Comment by melMass** [comment]
Thanks,

I know about MediaInfo, and I'm using the "Frame count" in python.
What would be the way to integrate values that you did not integrate (start_TC,duration_in_TC,frame count)?

**Comment by jeremyvizzini** [comment]
You are right. I read the python port and I added the possibility of retrieving all metadata. The only things you have to do is to git update and to put the following line before using the MIKMediaInfo class.

` [MIKMediaInfo enableAllMetadata:YES];`

Let me know if it is working.

**Comment by jeremyvizzini** [comment]
I will add the new constants as soon as possible.

**Comment by jeremyvizzini** [comment]
I added the constants. All should be fine now.

**Comment by melMass** [comment]
That was it ! Enabling all metas! 

Thanks.
